CREATE TABLE IF NOT EXISTS BuildNodes (
    Id          INTEGER PRIMARY KEY AUTOINCREMENT,
    PlayerRace  INTEGER NOT NULL DEFAULT 0,
    Matchups    INTEGER NOT NULL DEFAULT 0,
    ParentId    INTEGER REFERENCES BuildNodes(Id) ON DELETE CASCADE,
    Name        TEXT    NOT NULL DEFAULT '',
    Description TEXT    NOT NULL DEFAULT '',
    SortOrder   INTEGER NOT NULL DEFAULT 0
);
