CREATE TABLE IF NOT EXISTS GameBuilds (
    Id           INTEGER PRIMARY KEY AUTOINCREMENT,
    GamePlayerId INTEGER NOT NULL REFERENCES GamePlayers(Id) ON DELETE CASCADE,
    BuildId      INTEGER NOT NULL REFERENCES BuildNodes(Id) ON DELETE CASCADE,
    SortOrder    INTEGER NOT NULL DEFAULT 0,
    UNIQUE(GamePlayerId, BuildId)
);
